FROM node:18-alpine

WORKDIR /app

# Install dependencies based on the package.json file
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Copy the rest of the application code
COPY frontend .

# Build the Next.js application
RUN npm run build

# Expose the port used by Next.js
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start"]